apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: housing-price-api
  namespace: farisamz71-dev
  labels:
    app: housing-price-api
spec:
  output:
    to:
      kind: ImageStreamTag
      name: housing-price-api:latest
  source:
    type: Binary  # Changed from Git to Binary
    binary: {}    # Empty binary source
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
    - type: ConfigChange
    - type: ImageChange
  
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: housing-price-api
  namespace: farisamz71-dev
  labels:
    app: housing-price-api
spec:
  lookupPolicy:
    local: true