apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: housing-price-api
  namespace: farisamz71-dev
  labels:
    app: housing-price-api
spec:
  source:
    type: Git
    git:
      uri: https://github.com/your-username/housing-price-api.git
      ref: main
    contextDir: /
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: housing-price-api:latest
  triggers:
  - type: ConfigChange
  - type: ImageChange
  
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: housing-price-api
  namespace: farisamz71-dev
  labels:
    app: housing-price-api
spec:
  lookupPolicy:
    local: true