apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-pvc
  namespace: farisamz71-dev
  labels:
    app: housing-price-api
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3-csi  # Adjust based on your cluster's storage classes